apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alterai-pl
  namespace: webapp
spec:
  commonName: alterai.pl
  secretName: alterai-pl-tls
  dnsNames:
    - alterai.pl
  issuerRef:
    name: acme-prod
    kind: ClusterIssuer
