apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: webapp
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       80;
          server_name  alterai.pl;
          location /static {
            include /etc/nginx/mime.types;
            alias   /var/www/static;
            autoindex on;
        }
      }
    }