apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-secret
  namespace: webapp
  labels:
    app: postgres
data:
  POSTGRES_DB: ZGphbmdv
  POSTGRES_USER: ZGphbmdv
  POSTGRES_PASSWORD: ZGphbmdv
  PGDATA: L3Zhci9saWIvcG9zdGdyZXNxbC9kamFuZ28vZGF0YQ==