apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
  namespace: webapp
spec:
  template:
    spec:
      containers:
        - name: app
          image: alterius/webapp-backend
          imagePullPolicy: Always
          command: ["/bin/sh", "-c", "python manage.py makemigrations && python manage.py migrate"]
      restartPolicy: Never

